### ISSUE TITLE
Display options in help message in the declared order and not alphabetically

### ISSUE THREAD

**Issue by serba** [lexicalscope/jewelcli#16]
JewelCli users should be able to control the order of options displayed in help message. It seems the most easy and natural way is to display options in the order they defined in interface/class.

**Comment by lexicalscope** [comment]
Unfortunately JewelCli uses reflection to discover the methods in the interface; I originally considered using this reflection order to order the help messages - however the order is not guaranteed. Different JVMs can return the methods in different 
orders, so ordering the help messages in the order they are returned by reflection is unpredictable (see: http://docs.oracle.com/javase/6/docs/api/java/lang/Class.html#getDeclaredMethods%28%29).

I am open to suggestions on other ways to allow the order to be specified. I agree that it would be a useful feature, I just haven't come up with a neat way of doing it yet.

**Comment by serba** [comment]
Hmm, I thought since 1.6 order is not suaranteed by javadocs, but it is in practice (see http://stackoverflow.com/a/5004929/974768 ). Another solution is to have additional annotation/property, but that's more ugly. 

Thanks Tim for awesome library!

**Comment by lexicalscope** [comment]
In >=0.8.3 I have added a parameter to @CommandLineInterface which allows you to disable the alphabetical sorting of the options. Setting the "order" parameter to OptionOrder.DEFINITION should cause JewelCli to use whatever ordering the underlying JVM reflection implementation uses for methods.
