### ISSUE TITLE
ClassCastException when defining list subclasses

### ISSUE THREAD

**Issue by bethard** [lexicalscope/jewelcli#20]
If I try to define a ListSubclass with a single String parameter that does some parsing, I get a ClassCastException. Here's the sample code:

```
public static class MyList extends ArrayList<String> {
  public MyList(String string) {
    this.addAll(Arrays.asList(string.split(";;")));
  }
}
public interface Options {
  @Option
  MyList getList();
}
public static void main(String[] args) {
  Options options = CliFactory.parseArguments(Options.class, args);
  System.err.println(options.getList());
}
```

And here's the exception:

```
Exception in thread "main" java.lang.ClassCastException: java.util.LinkedList cannot be cast to Bug$MyList
at $Proxy4.getList(Unknown Source)
at Bug.main(Bug.java:22)
```

Seems like maybe it's testing whether MyList is a subclass of List, when it really should be checking if MyList is a superclass of LinkedList. Also, since MyList has a constructor with a single String argument, shouldn't that just be used instead?

**Comment by lexicalscope** [comment]
thanks. fixed in versions after 0.8.4
