### ISSUE TITLE
Extend enum support to allow it to return the specified Enum value

### ISSUE THREAD

**Issue by krishofmans** [lexicalscope/jewelcli#22]
Hello,

I saw ticket #4 where a boolean is used to get a certain enum value.
It would be nice to have an option to specify one string value of an enum and get the typed Enum value from the interface.

I have worked around this by doing:
    @Option(shortName = "r", description = "value should be either: 'stopYYYStartXXX' or 'stopXXXstartYYY'")
    ScenarioEnumWrapper getScenario();

```
public class ScenarioEnumWrapper extends EnumWrapper<Scenario> {
    public ScenarioEnumWrapper(final String value) {
        super(value);
    }
}
```

and then:
public abstract class EnumWrapper<T extends Enum<?>> {
    private final T enumValue;

```
@SuppressWarnings({ "unchecked", "rawtypes" })
public EnumWrapper(final String value) {
    final List<Class<?>> classes = getTypeArguments(EnumWrapper.class, this.getClass());

    enumValue = (T) Enum.valueOf((Class) classes.get(0), value);
}

public T getValue() {
    return enumValue;
}
```

}

where the getTypeArguments is a whole lot of reflection magic going on to extract the value from T, it works, yet it would be nice if it could be hidden more inside jewelcli, so that I no longer have to get the ScenarioEnumWrapper I could just get the Scenario from a commandline value. It should even be easier to implement inside your proxy since you have the GenericReturnType of the Method in question all you need to do is return Enum.getValue(genericReturnType.class, incomingValue); and you don't need any special reflection tricks.

I might look into writing a patch.

Kris

**Comment by lexicalscope** [comment]
I'm a bit confused. I don't think a boolean is used in issue #4 for anything other than to make the option "optional" (as opposed to mandatory); it certainly isn't used to encode the enum value. 

Does the following not work?

```
 @Option(shortName = "r", description = "value should be either: 'stopYYYStartXXX' or 'stopXXXstartYYY'") Scenario getScenario();
```

I may have missed understood your issue report?

**Comment by krishofmans** [comment]
okay, the return of the enum is working, there was another issue at the same time causing it not to work, everything is working fine now, my apologies.
