### ISSUE TITLE
OptionOrder.LEXICOGRAPHIC sorts by method name, not longName

### ISSUE THREAD

**Issue by cambecc** [lexicalscope/jewelcli#24]
It appears the default option ordering, `OptionOrder.LEXICOGRAPHIC`, sorts options based on the bean-style name of the method rather than the `longName` field of the `Option` annotation.

For example:

```
@CommandLineInterface(application="test")
public interface Test {

    @Option(longName="a")
    boolean getZ();

    @Option(longName="z")
    boolean getA();
}
```

Associated help message:

```
Usage: test [options]
    [--z]
    [--a]
```

**Comment by lexicalscope** [comment]
Hmm, this definitely doesn't seem right. I will try to make some time to
fix this. In the mean time, if anyone else reading this wants to have a go
at fixing it then let me know.

**Comment by lexicalscope** [comment]
should sync to maven central shortly

**Comment by cambecc** [comment]
Works great. Thanks!
