### ISSUE TITLE
boolean flag does not work with "shortName"

### ISSUE THREAD

**Issue by stepinto** [lexicalscope/jewelcli#26]
The below code will throw NPE when accessing cli.f(). 
If I rename f() to getF(), everything works well.

```
interface CliOptions {
    @Option(shortName = "f")
    boolean f();
}

public static void main(String[] args) {
    CliOptions cli = CliFactory.parseArguments(CliOptions.class, "-f");
    System.out.println("cli.f() = " + cli.f());
}
```

**Comment by lexicalscope** [comment]
I think this is unrelated to shortName. I think it is a problem related to distinguishing if this "f" method is a flag or an option with a value. I am investigating further.

**Comment by lexicalscope** [comment]
0.8.7 should be available in maven central when it syncs from oss.sonatype.org
