### ISSUE TITLE
Multiple shortName Being Ignored

### ISSUE THREAD

**Issue by graywolf336** [lexicalscope/jewelcli#28]
I have been looking at implementing this into my plugin for Bukkit (Minecraft server api) and was testing it out before I actually started using it. When doing so I made some unit tests and found something which looks like a bug but might be my ignorance on the usage.  Here is the interface I am using:

``` java
public interface Jailing {
    @Option(shortName={"player", "pl", "p"})
    String getPlayer();
}
```

And here is the unit tests:

``` java
public class TestJewel {
    @Test
    public void testJewel() {
        String[] args = { "-pl", "graywolf336" };
        Jailing j = CliFactory.parseArguments(Jailing.class, args);

        Assert.assertEquals("graywolf336", j.getPlayer());
    }
}
```

And the result is an argument validation exception message which is wrong:

``` java
com.lexicalscope.jewel.cli.ArgumentValidationException: Option must have a value: --player -p -p -p value
Unexpected Option: l
    at com.lexicalscope.jewel.cli.ValidationErrorBuilderImpl.validate(ValidationErrorBuilderImpl.java:64)
    at com.lexicalscope.jewel.cli.validation.ArgumentValidatorImpl.finishedProcessing(ArgumentValidatorImpl.java:66)
    at com.lexicalscope.jewel.cli.ArgumentCollectionBuilder.processArguments(ArgumentCollectionBuilder.java:129)
    at com.lexicalscope.jewel.cli.AbstractCliImpl.parseArguments(AbstractCliImpl.java:42)
    at com.lexicalscope.jewel.cli.CliFactory.parseArguments(CliFactory.java:67)
    at test.java.com.graywolf336.jail.TestJewel.testJewel(TestJewel.java:14)
```

To my understanding of how this works, how I've got it setup and parsing it this should work. Am I missing something or this actually a bug?

**Comment by lexicalscope** [comment]
Short names are a single character and can be written next to each other so:
     -pl
is interpreted as being equivalent to
     -p -l

This is based on how I think GNU getopt based utilities work, for example
the unix "tar" command where you can write "tar -zxf myfile.tar.gz" instead
of "tar -z -x -f myfile.tar.gz"

You would have to do
      @Option(longName={"player", "pl"}, shortName={"p"})
Which would let you write "--player" or "--pl" or "-p". I hope that isn't
too much of an issue for you? I did start working on making the argument
parsing pluggable, but I do not have enough time available to finish that
work at the moment.

JewelCli should probably throw an exception if the shortName isn't a single
character....

**Comment by graywolf336** [comment]
That makes sense as to why it is doing it, sadly that's not going to work for me. I was hoping I was able to define as many shortName as possible so we could use the `-pl` alongside `-p` and `-player`, as younger people are the target of what I'm doing and it'd just confuse them having to do `--`. Guess we'll be stuck with using the one short value, unless you have any suggestions?

**Comment by lexicalscope** [comment]
Unfortunately not, at the moment the argument parser is really designed to
work in the single/double dash style. It would require a new version of
JewelCli to be built to support your scheme.

In order to support different parser styles, someone would have to write a
version of com.lexicalscope.jewel.cli.parser.ArgumentParserImpl
implementing  com.lexicalscope.jewel.cli.parser.ArgumentParser that
supported the new parsing scheme.

And then add a new CliFactory entry point to allow that custom
ArgumentParser to be passed to com.lexicalscope.jewel.cli.AbstractCliImpl.

**Comment by graywolf336** [comment]
Alright, thanks for your help. I'll probably just have to end up going with the single character versions.
