### ISSUE TITLE
Repeatedly calling interface's method causes memory leak

### ISSUE THREAD

**Issue by stepinto** [lexicalscope/jewelcli#29]
My program repeatedly in call the jewelcli's generated object in a loop. I found this will lead to memory leak. It seems to me that jewelcli creates something every time when the method is called, rather than cache the parsed value.

Here is jmap's output. 
##  num     #instances         #bytes  class name

   1:       7420760      653026880  java.lang.reflect.Method
   2:       1679510      316381800  [B
   3:      10261545      234341328  [Ljava.lang.Class;
   4:        681145      186828472  [I
   5:       5801706      185654592  java.util.AbstractList$Itr
   6:       3092467       98958944  com.lexicalscope.jewelcli.internal.fluentreflection.$FluentClassImpl
   7:       3092467       98958944  com.lexicalscope.jewelcli.internal.fluentreflection.$ReflectedMembersImpl
   8:       3092467       98958944  com.lexicalscope.jewelcli.internal.fluentreflection.$ReflectedMethodsImpl
   9:       3672323       88135752  com.lexicalscope.jewelcli.internal.guice.$TypeLiteral
  10:       3672310       88135440  com.lexicalscope.jewelcli.internal.fluentreflection.$FluentAnnotatedImpl
  11:       3092467       74219208  com.lexicalscope.jewelcli.internal.fluentreflection.$ReflectedFieldsImpl
  12:       3092467       74219208  com.lexicalscope.jewelcli.internal.fluentreflection.$ReflectedSuperclassesAndInterfacesImpl
  13:       3092467       74219208  com.lexicalscope.jewelcli.internal.fluentreflection.$ReflectedConstructorsImpl

**Comment by lexicalscope** [comment]
Can you show me what loop you ran?

**Comment by lexicalscope** [comment]
Also please tell me the version number you are using?

**Comment by stepinto** [comment]
Hi @lexicalscope, thanks for your quick response. Unfortunately, I cannot reproduce it now. My program is very simple. Let me close this issue now.
